// <auto-generated />
using GolfAppAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GolfAppAPI.Migrations
{
    [DbContext(typeof(GolfAppDbContext))]
    [Migration("20260627004704_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GolfAppAPI.Models.Course", b =>
                {
                    b.Property<int>("courseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("courseId"));

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("latitude")
                        .HasColumnType("real");

                    b.Property<float>("longitude")
                        .HasColumnType("real");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("state")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("courseId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("GolfAppAPI.Models.CourseHole", b =>
                {
                    b.Property<int>("courseHoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("courseHoleId"));

                    b.Property<int>("courseHoleNumber")
                        .HasColumnType("int");

                    b.Property<int>("courseId")
                        .HasColumnType("int");

                    b.Property<float>("greenLatitude")
                        .HasColumnType("real");

                    b.Property<float>("greenLongitude")
                        .HasColumnType("real");

                    b.Property<int>("par")
                        .HasColumnType("int");

                    b.Property<float>("teeLatitude")
                        .HasColumnType("real");

                    b.Property<float>("teeLongitude")
                        .HasColumnType("real");

                    b.HasKey("courseHoleId");

                    b.HasIndex("courseId");

                    b.ToTable("CourseHoles");
                });

            modelBuilder.Entity("GolfAppAPI.Models.CourseHole", b =>
                {
                    b.HasOne("GolfAppAPI.Models.Course", "Course")
                        .WithMany("CourseHoles")
                        .HasForeignKey("courseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("GolfAppAPI.Models.Course", b =>
                {
                    b.Navigation("CourseHoles");
                });
#pragma warning restore 612, 618
        }
    }
}
